name: app_gntech

services:
  gntech_mysql:
    image: mysql:8.0
    container_name: gntech_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gntech_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  gntech_backend:
    build: ./backend
    container_name: gntech_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@gntech_mysql:3306/gntech_db
      - OPENWEATHER_API_KEY=6f09094cb376fcbc0a49d8ed7a3a97be
    depends_on:
      gntech_mysql:
        condition: service_healthy

volumes:
  mysql_data: